Contact form
JOdiemo/mobile-contact-form pull request #1
Opened 2022-06-08 14:30 UTC by JOdiemo

Create forms with HTML5 validations.
Understand the importance of UX.
Understand how to parse a Figma design to create a UI.

2022-06-08 14:44 UTC, ShoiraTa requested changes
Hi @JOdiemo,
:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

**First let me to point out:**

- Great commit history! ✔️ 
- You passed all the Linters! ✔️ 
- Professional pull request! ✔️ 

Keep on coding, good job so far! :clap:

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-08 14:44 UTC, ShoiraTa commented on index.html
> +                  </form>
- [ ] Form works well, it meets the requirements of validations and input types. But the design is different from the one provided in Figma: 

Your design  | Figma design
------------- | -------------
<img width="408" alt="Screenshot 2022-06-08 at 18 35 48" src="https://user-images.githubusercontent.com/77038610/172643879-fd42f6da-eb00-478b-bbf2-10c98da2a66d.png">  | <img width="310" alt="Screenshot 2022-06-08 at 18 35 29" src="https://user-images.githubusercontent.com/77038610/172643807-8d4f0a88-5653-4d20-923d-82318bbf6df2.png">

### Please note that for this project you have to strictly stick to Figma template design, 

- [ ] Please make sure that the form stretches from theft to right without whitespace around.
- [ ] Kindly follow the design guidelines, set the same colors, font size, margins paddings. 
- [ ] Please set less border radius on input elements,

2022-06-08 14:44 UTC, ShoiraTa commented on index.html
> +
- [ ] Button interactions such as hover, active (when it's pressed), disabled and enable (default state) are styled as shown in the Figma template.
<img width="733" alt="Screenshot 2022-06-08 at 18 40 20" src="https://user-images.githubusercontent.com/77038610/172644896-9eb7a45a-5738-45e5-a68a-345de4eb14e9.png">

Currently when I hover on your page: 
<img width="202" alt="Screenshot 2022-06-08 at 18 40 47" src="https://user-images.githubusercontent.com/77038610/172644989-5381e39b-a960-4387-9901-76b8d2c64b8e.png">

As you can see the colors are different, kindly make sure to have same interaction effects

2022-06-08 14:44 UTC, ShoiraTa commented on README.md
>  [Live Demo Link](https://livedemo.com)
- [ ] Please make sure to customise the README template, I can see that some unused sections were not cleared: 
<img width="1063" alt="Screenshot 2022-06-08 at 18 42 48" src="https://user-images.githubusercontent.com/77038610/172645467-dc2f4528-ac38-41e4-9317-be033a21edcf.png">

Please customize this section by adding proper steps to get started.

2022-06-09 06:32 UTC, Ismailco requested changes
### Hi @JOdiemo,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-09 06:32 UTC, Ismailco commented on README.md
>  ## Live Demo (if available)
- [ ] As the previous reviewer mentioned, kindly customize the README. you can remove the unused headers/sections, from the line `18` to line `36`
```
## Getting Started
**This is an example of how you may give instructions on setting up your project locally.**
**Modify this file to match your project, remove sections that don't apply. For example: delete the testing section if the currect project doesn't require testing.**
To get a local copy up and running follow these simple example steps.
### Prerequisites
### Setup
### Install
### Usage
### Run tests
### Deployment
```

2022-06-09 06:32 UTC, Ismailco commented on index.html
> +               </div>
- [ ] The previous reviewer mentioned that the form design is not the same as the Figma design, kindly modify it so it's closer to the provided design as possible

|Your design|Figma design|
|-|-|
|![Screenshot_20220609_072236](https://user-images.githubusercontent.com/25227022/172779727-9a325b82-827c-469c-a11a-a0f4da89e9ec.png)|<img width="310" alt="172643807-8d4f0a88-5653-4d20-923d-82318bbf6df2" src="https://user-images.githubusercontent.com/25227022/172779815-6022d630-1096-47bb-9990-cb5e3f13d575.png">|

2022-06-09 10:54 UTC, t-yanick approved these changes
Hi @JOdiemo, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-09 10:54 UTC, t-yanick commented on README.md
>  ## Authors
- [OPTIONAL] Please kindly update the `Authors section` with your information, as this will make your readme file more informative and professional.

2022-06-09 10:58 UTC, merged